language: ruby
rvm:
  - 1.9.3

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle exec ruby ./test/app.rb &
  - sleep 3

script: phantomjs ./test/run-qunit.js "http://localhost:4567/"

notifications:
  email: false
